export const MARKET = {
    GET_MARKET_SYMBOLS: 'MARKET_GET_MARKET_SYMBOLS',
    SET_MARKET_SYMBOLS: 'MARKET_SET_MARKET_SYMBOLS',
    GET_WATCHLIST: 'MARKET_GET_WATCHLIST',
    SET_WATCHLIST: 'MARKET_SET_WATCHLIST',
    GET_SINGLE_SYMBOL: 'MARKET_GET_SINGLE_SYMBOL',
    SET_SINGLE_SYMBOL: 'MARKET_SET_SINGLE_SYMBOL'
};
